# Generated by Django 5.2.13 on 2026-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exporttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
