# Generated by Django 5.2.13 on 2026-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0002_savedsearch'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='filing',
            new_name='filings_fil_filing__8983ea_idx',
            old_name='filings_fil_date_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='filing',
            new_name='filings_fil_industr_5d6379_idx',
            old_name='filings_fil_ind_date_idx',
        ),
        migrations.RenameIndex(
            model_name='issuer',
            new_name='filings_iss_state_b1ae9d_idx',
            old_name='filings_iss_state_idx',
        ),
        migrations.RenameIndex(
            model_name='relatedperson',
            new_name='filings_rel_filing__ac39a2_idx',
            old_name='filings_rp_filing_idx',
        ),
        migrations.AlterField(
            model_name='filing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issuer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relatedperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
