# Generated by Django 5.2.13 on 2026-04-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0004_issuerwatch_issuer_normalized_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerwatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
