# Generated by Django 5.2.13 on 2026-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filings', '0010_filing_banker'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='issuerview',
            new_name='filings_iss_user_id_0a00b2_idx',
            old_name='filings_iss_user_id_viewed_idx',
        ),
        migrations.AddField(
            model_name='issuer',
            name='inferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='inferred_website',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='issuerview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
